### ISSUE TITLE
源码拼写错误

### ISSUE THREAD

**Issue by MPGInfninity** [7777a2333/MinecraftServerDownloader#1]
路径 `src/ServerDownloadEr.java`

第 28 行

```java
System.out.println("1   原版服务端   2 Purpur服务端(Parper分支)  3   Spigot服务端   4 CarftBukkit服务端");
```

应该为

```java
System.out.println("1   原版服务端   2 Purpur服务端(Parper分支)  3   Spigot服务端   4 CraftBukkit服务端");
```

还有第二个我不确定，Purpur我感觉是Paper分支（我也不知道）

**Comment by 7777a2333** [comment]
收到，发现4 2拼写均错误，下个版本修复
应为`System.out.println("1   原版服务端   2 Purpur服务端(Paper分支)  3   Spigot服务端   4 CraftBukkit服务端"); `
感谢你的贡献

**Comment by 7777a2333** [comment]
v1.4.1已修复
感谢你的贡献

**Comment by 7777a2333** [comment]
v1.4.1已修复
感谢你的贡献
